### ISSUE TITLE
Simplify configuration for JWT identity provider signing keys

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#68]
Zilla supports JWT authorization and requires the public signing keys from the JWT identity provider to verify token integrity.
```
    "guards":
    {
        "jwt0":
        {
           "type":"jwt",
           "options":
           {
              "issuer": "https://auth.example.com/",
              "audience": "https://api.example.com/",
              "keys":
              [
                  ...
              ]
           }
        }
    }
```
This requires copying the contents of the identity provider supplied JSON Web Key Set (JWKS).

However, identity providers can rotate their signing keys, requiring the configuration to be updated.

Instead, we can add support for specifying the URL where the JSON Web Key Set can be retrieved.

```
    "guards":
    {
        "jwt0":
        {
           "type":"jwt",
           "options":
           {
              "issuer": "https://auth.example.com/",
              "audience": "https://api.example.com/",
              "keys": "https://auth.example.com/.well-known/jwks.json"
           }
        }
    }
```

In fact, we can derive a default value for `keys` URL by appending `.well-known/jwks.json` to the `issuer` URL, making it unnecessary to specify the `keys` in the configuration.

```
    "guards":
    {
        "jwt0":
        {
           "type":"jwt",
           "options":
           {
              "issuer": "https://auth.example.com/",
              "audience": "https://api.example.com/"
           }
        }
    }
```

The `keys` URL can be resolved when parsing configuration on startup.

Systems that prefer to configure the `keys` explicitly can still do so using the existing syntax.

**Comment by Alfusainey** [comment]
@jfallows I want to wrap my head around the Zilla code base by working on this issue. Can I give it a try?

So the idea is to populate the `JwtOptionsConfig#keys` field upon startup when a URL (instead of a JSON array) is provided as the value for `keys`? So basically, the logic to do so should preferably be in `JwtOptionsConfigAdapter#adaptFromJson`:

```java
...
 List<JwtKeyConfig> keys = object.containsKey(KEYS_NAME)
                ? object.getJsonArray(KEYS_NAME)
                    .stream()
                    .map(JsonValue::asJsonObject)
                    .map(key::adaptFromJson)
                    .collect(toList())
                : KEYS_DEFAULT;
...
```
Or should this happen much earlier up?

Also, if the key is missing, an empty list of JwtKeyConfig is currently returned. But a missing key can now mean that the JWKS should be retrieved using `https://auth.example.com/.well-known/jwks.json`. 

So one approach that immediately comes to mind is the following: if the key is missing in the JSON file, then attempt to retrieve the JWKS using `$issuer/.well-known/jwks.json`. This should return the data if the configured identity provider implements the OIDC Discovery specification. But since this spec is optional, it could be that a configured provider does not provide support for retrieving its JWKS. In that case, we return a default empty list (as is done currently).

what do you think?

**Comment by Alfusainey** [comment]
@jfallows or is this issue already assigned to someone?

**Comment by jfallows** [comment]
@Alfusainey thanks for the detailed suggested approach.

Let's discuss the design here and by all means you should have a go at a PR for this. 👍 

The first step would be to define the change in JSON schema needed to represent this approach, see `specs/guard-jwt.spec/src/main/scripts/io/aklivity/zilla/specs/guard/jwt/schema/jwt.schema.patch.json`.
We'll need some specific configurations and `SchemaTest` test case methods to verify the enhanced syntax.

An initial draft PR with the proposed JSON Schema changes would be great!

You are right to say that `JwtOptionsConfig` is the strongly typed representation of this in memory, and we can attempt to resolve the `.jwks` URL during parsing. Ideally, I'd like to be able to pass some sort of `resolver` from `ConfigureTask` during parse that would delegate the machinery of `URLConnection` to the caller instead of individual options adapters.

**Comment by Alfusainey** [comment]
@jfallows awesome, you just wished me a nice weekend, thanks! will be working on this

**Comment by Alfusainey** [comment]
@jfallows I implemented this but its a hack: I resolve the `.jwks`  URL inside the JWT options config adapter.  I think this is not what you have in mind:

> Ideally, I'd like to be able to pass some sort of resolver from ConfigureTask during parse that would delegate the machinery of URLConnection to the caller instead of individual options adapters.

If you say delete to the caller, do you mean the `ConfigureTask` ?

**Comment by jfallows** [comment]
> @jfallows I implemented this but its a hack: I resolve the `.jwks` URL inside the JWT options config adapter. I think this is not what you have in mind:
> 
> > Ideally, I'd like to be able to pass some sort of resolver from ConfigureTask during parse that would delegate the machinery of URLConnection to the caller instead of individual options adapters.
> 
> If you say delete to the caller, do you mean the `ConfigureTask` ?

@Alfusainey Yep, delegate to ConfigureTask so it can resolve relative to the original root URL if relative.
